
language: scala
jdk: oraclejdk8
scala:
   - 2.12.2

script:
 - sbt clean coverage test
 - if [ "$TRAVIS_BRANCH" == "master" ]; then
      TAG=`cat version`;
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
      CONTAINER_NAME=$DOCKER_USERNAME/cs-vault-server;
      docker build -t $CONTAINER_NAME:latest .;
      docker images;
      docker push $CONTAINER_NAME:latest;
      docker tag $CONTAINER_NAME $CONTAINER_NAME:$TAG;
      docker push $CONTAINER_NAME:$TAG;
    fi

after_success: "sbt coverageReport coveralls"
