
language: scala
jdk: oraclejdk8
scala:
   - 2.12.2

script:
 - sbt clean coverage test
 - if [ "$TRAVIS_BRANCH" == "master" ]; then
      TAG=`cat version`
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
      docker build -t cs-vault-server .;
      docker images;
      docker tag cs-vault-server $DOCKER_USERNAME/cs-vault-server:$TAG;
      docker push $DOCKER_USERNAME/cs-vault-server:$TAG;
    fi

after_success: "sbt coverageReport coveralls"
